create database Hospital;

create table Convenio(
	COD_CONVENIO INT PRIMARY KEY,
	CPF_PACI VARCHAR(12),
	NOME_CONVENIO VARCHAR(20),
	CNPJ VARCHAR(20),
	TEMPO_CARENCIA VARCHAR(20),
	FOREIGN KEY(CPF_PACI) REFERENCES PACIENTE(CPF_PACI)
);


CREATE TABLE PACIENTE(
	CPF_PACI VARCHAR(12) PRIMARY KEY,
	NOME_PACI VARCHAR(100),
	RG_PACI VARCHAR(10),
	DATA_NASCI DATE,
	ENDERECO_PACI VARCHAR(30),
	TELEFONE_PACI VARCHAR(20),
	EMAIL_PACI VARCHAR(20),
	COD_CONVENIO INT,
	FOREIGN KEY(COD_CONVENIO) REFERENCES CONVENIO(COD_CONVENIO)

);

select * from PACIENTE;

ALTER TABLE QUARTO DROP CONSTRAINT FK__QUARTO__CPF_PACI__5AEE82B9;
ALTER TABLE RECEITA DROP CONSTRAINT FK__RECEITA__CPF_PAC__534D60F1;
ALTER TABLE INTERNACAO DROP CONSTRAINT FK__INTERNACA__CPF_P__4BAC3F29;
ALTER TABLE CONSULTA DROP CONSTRAINT FK__CONSULTA__CPF_PA__47DBAE45;

ALTER TABLE Convenio DROP CONSTRAINT FK_PACIENTE;

ALTER TABLE PACIENTE 
ALTER COLUMN email_paci VARCHAR(100);


ALTER TABLE PACIENTE DROP CONSTRAINT PK__PACIENTE__72789C42DC63E753;
ALTER TABLE PACIENTE 
ALTER COLUMN cpf_paci VARCHAR(20) NOT NULL;

ALTER TABLE PACIENTE 
ADD CONSTRAINT PK__PACIENTE__72789C42DC63E753 PRIMARY KEY (cpf_paci);



ALTER TABLE QUARTO 
ADD CONSTRAINT FK__QUARTO__CPF_PACI__5AEE82B9 FOREIGN KEY (cpf_paci) REFERENCES PACIENTE(cpf_paci);

ALTER TABLE RECEITA 
ADD CONSTRAINT FK__RECEITA__CPF_PAC__534D60F1 FOREIGN KEY (cpf_paci) REFERENCES PACIENTE(cpf_paci);

ALTER TABLE CONSULTA 
ADD CONSTRAINT FK__CONSULTA__CPF_PACI__47DBAE45 FOREIGN KEY (cpf_paci) REFERENCES PACIENTE(cpf_paci);

ALTER TABLE INTERNACAO 
ADD CONSTRAINT FK__INTERNACA__CPF_P__4BAC3F29 FOREIGN KEY (cpf_paci) REFERENCES PACIENTE(cpf_paci);

ALTER TABLE Convenio ALTER COLUMN CPF_PACI VARCHAR(20);


-- Modificar a tabela QUARTO
ALTER TABLE QUARTO 
ALTER COLUMN CPF_PACI VARCHAR(20) NOT NULL;

-- Modificar a tabela CONSULTA
ALTER TABLE CONSULTA 
ALTER COLUMN CPF_PACI VARCHAR(20) NOT NULL;

-- Modificar a tabela RECEITA
ALTER TABLE RECEITA 
ALTER COLUMN CPF_PACI VARCHAR(20) NOT NULL;

-- Modificar a tabela INTERNACAO
ALTER TABLE INTERNACAO 
ALTER COLUMN CPF_PACI VARCHAR(20) NOT NULL;




CREATE TABLE MEDICO(
	NUM_CRM VARCHAR(20),
	NOME_MED VARCHAR(30),
	ENDERECO_MED VARCHAR(30),
	EMAIL_MED VARCHAR(20),
	DATA_NASCI DATE,
	TELEFONE_MED VARCHAR(15),
	PRIMARY KEY(NUM_CRM)
);

select*from MEDICO;


CREATE TABLE Generalista (
    COD_Generalista INT,
    NUM_CRM VARCHAR(20),
	PRIMARY KEY(COD_Generalista,NUM_CRM),
    FOREIGN KEY (NUM_CRM) REFERENCES Medico(NUM_CRM)
);

SELECT * FROM Generalista;

CREATE TABLE Especialista (
    COD_Especialista INT,
    NUM_CRM VARCHAR(20),
	PRIMARY KEY(COD_ESPECIALISTA),
    FOREIGN KEY (NUM_CRM) REFERENCES Medico(NUM_CRM)
);

SELECT * FROM Especialista;

CREATE TABLE ESPECIALIDADE(
	COD_ESPECIALIDADE INT,
	COD_ESPECIALISTA INT,
	NOME_ESPECIALIDADE VARCHAR(30),
	PRIMARY KEY(COD_ESPECIALIDADE),
	FOREIGN KEY(COD_ESPECIALISTA) REFERENCES ESPECIALISTA(COD_Especialista)
);

SELECT * FROM ESPECIALIDADE;

CREATE TABLE Residente (
    COD_Residente INT,
    NUM_CRM VARCHAR(20),
	PRIMARY KEY(COD_RESIDENTE,NUM_CRM),
    FOREIGN KEY (NUM_CRM) REFERENCES Medico(NUM_CRM)
);

SELECT * FROM Residente;

CREATE TABLE MEDICO_CONVENIO(
	NUM_CRM VARCHAR(20),
	COD_CONVENIO INT,
	PRIMARY KEY(NUM_CRM,COD_CONVENIO),
	FOREIGN KEY(NUM_CRM) REFERENCES MEDICO(NUM_CRM),
	FOREIGN KEY(COD_CONVENIO) REFERENCES CONVENIO(COD_CONVENIO)
);

SELECT * FROM MEDICO_CONVENIO;

CREATE TABLE ENFERMEIRO(
	COD_ENFERMEIRO INT,
	NUM_COREN VARCHAR(20),
	NOME VARCHAR(30),
	CPF VARCHAR(12),
	PRIMARY KEY(COD_ENFERMEIRO)
);

CREATE TABLE INTERNAÇÃO_ENFERMEIRO (
    COD_INTERNACAO INT,
    COD_ENFERMEIRO INT,
    PRIMARY KEY(COD_INTERNACAO, COD_ENFERMEIRO),
    FOREIGN KEY(COD_INTERNACAO) REFERENCES INTERNACAO(COD_INTERNACAO),
    FOREIGN KEY(COD_ENFERMEIRO) REFERENCES ENFERMEIRO(COD_ENFERMEIRO)
);


SELECT * FROM ENFERMEIRO;

alter table Enfermeiro
ALTER COLUMN cpf VARCHAR(20);

CREATE TABLE ENFERMEIRO_INTERNACAO(
	COD_ENFERMEIRO INT,
	COD_INTERNACAO INT,
	PRIMARY KEY(COD_ENFERMEIRO,COD_INTERNACAO),
	FOREIGN KEY(COD_ENFERMEIRO) REFERENCES ENFERMEIRO(COD_ENFERMEIRO),
	FOREIGN KEY(COD_INTERNACAO) REFERENCES INTERNACAO(COD_INTERNACAO)
);

SELECT * FROM ENFERMEIRO_INTERNACAO;

CREATE TABLE QUARTO(
	COD_QUARTO INT,
	CPF_PACI VARCHAR(12),
	NUM_QUARTO VARCHAR(10),
	COD_INTERNACAO INT,
	TIPO VARCHAR(20)
	PRIMARY KEY(COD_QUARTO),
	FOREIGN KEY(CPF_PACI) REFERENCES PACIENTE(CPF_PACI),
	FOREIGN KEY(COD_INTERNACAO) REFERENCES INTERNACAO(COD_INTERNACAO)
);

SELECT * FROM QUARTO;
delete TIPO_QUARTO


CREATE TABLE TIPO_QUARTO(
	COD_TIPO_QUARTO INT,
	COD_QUARTO INT,
	VALOR_DIARIO DECIMAL,
	DESCRICAO VARCHAR(100),
	PRIMARY KEY(COD_TIPO_QUARTO),
	FOREIGN KEY(COD_QUARTO) REFERENCES QUARTO(COD_QUARTO)
);

SELECT * FROM TIPO_QUARTO;



CREATE TABLE CONSULTA(
	COD_CONSULTA INT,
	COD_CONVENIO INT,
	DATA_CONSULTA DATE,
	HORARIO TIME,
	NUM_CARTEIRA INT,
	COD_ESPECIALIDADE INT,
	NUM_CRM VARCHAR(20),
	CPF_PACI VARCHAR(12),
	PRIMARY KEY(COD_CONSULTA),
	FOREIGN KEY(COD_ESPECIALIDADE) REFERENCES ESPECIALIDADE(COD_ESPECIALIDADE),
	FOREIGN KEY(NUM_CRM) REFERENCES MEDICO(NUM_CRM),
	FOREIGN KEY(CPF_PACI) REFERENCES PACIENTE(CPF_PACI),
	FOREIGN KEY(COD_CONVENIO) REFERENCES CONVENIO(COD_CONVENIO)
);

SELECT * FROM CONSULTA;
ALTER TABLE consulta ALTER COLUMN CPF_PACI VARCHAR(100);

CREATE TABLE COBRE(
	COD_CONVENIO INT,
	COD_CONSULTA INT,
	VALOR_CONSULTA DECIMAL(10,2),
	PRIMARY KEY (Cod_Convenio, Cod_Consulta),
    FOREIGN KEY (Cod_Convenio) REFERENCES Convenio(Cod_Convenio),
    FOREIGN KEY (Cod_Consulta) REFERENCES Consulta(Cod_Consulta)
);

SELECT * FROM COBRE;

CREATE TABLE RECEITA(
	COD_RECEITA INT,
	COD_CONSULTA INT,
	CPF_PACI VARCHAR(12),
	INSTRUCOES VARCHAR(200),
	QUANTIDADE VARCHAR(50),
	MEDICAMENTO VARCHAR(50),
	PRIMARY KEY(COD_RECEITA),
	FOREIGN KEY(COD_CONSULTA) REFERENCES CONSULTA(COD_CONSULTA),
	FOREIGN KEY(CPF_PACI) REFERENCES PACIENTE(CPF_PACI)
);

SELECT * FROM RECEITA;

CREATE TABLE Recebimento (
    ID_Recebimento INT PRIMARY KEY,
    Data_Recebimento DATE
);

SELECT * FROM Recebimento;


CREATE TABLE Recebimento_Email (
    ID_Recebimento INT PRIMARY KEY,
    EMAIL_PACI VARCHAR(40),
    FOREIGN KEY (ID_Recebimento) REFERENCES Recebimento(ID_Recebimento),
);



SELECT EMAIL_PACI FROM paciente;


SELECT * FROM Recebimento_Email;

-- Tabela para Impresso
CREATE TABLE Recebimento_Impresso (
    ID_Recebimento INT PRIMARY KEY,
    Endereco VARCHAR(255),
    FOREIGN KEY (ID_Recebimento) REFERENCES Recebimento(ID_Recebimento)
);

SELECT * FROM Recebimento_Impresso;

CREATE TABLE INTERNACAO(
	COD_INTERNACAO INT,
	CPF_PACI VARCHAR(20),
	NUM_CRM VARCHAR(20),
	DATA_ENTRADA DATE,
	DATA_ALTA DATE,
	DATA_PREV_ALTA DATE,
	PROCEDIMENTO VARCHAR(300),
	PRIMARY KEY(COD_INTERNACAO),
	FOREIGN KEY(CPF_PACI) REFERENCES PACIENTE(CPF_PACI),
	FOREIGN KEY(NUM_CRM) REFERENCES MEDICO(NUM_CRM)
);

ALTER TABLE INTERNACAO
ALTER COLUMN CPF_PACI VARCHAR(100);

alter table internacao
add cod_quarto int;

ALTER TABLE internacao 
ADD CONSTRAINT cod_quarto FOREIGN KEY (cod_quarto) REFERENCES quarto(cod_quarto);

SELECT * FROM INTERNACAO;
